import R from "../lib/R.js";
import { IT, IT2 } from "./TonyuIterator.js";
import { TonyuThread } from "./TonyuThread.js";
import { ClassDefinition, ClassTreeRoot, Meta, ProjectOptions, TonyuClass, TonyuShimClass } from "./RuntimeTypes.js";
import TError from "./TError.js";
declare function thread(): TonyuThread;
declare function timeout(t: number): Promise<unknown>;
declare function addMeta(fn: string, m: Partial<Meta>): Meta;
declare function bless(klass: TonyuShimClass | null, val: object): any;
declare function extend(dst: any, src: any): any;
declare function setGlobal(n: string, v: any): void;
declare function getGlobal(n: string): any;
declare function getClass(n: string): TonyuClass | undefined;
declare function bindFunc(t: object, meth: any): any;
declare function invokeMethod(t: object, name: string, args: any[], objName: string): any;
declare function callFunc(f: Function, args: any[], fName: string): any;
declare function checkNonNull(v: any, name: string): any;
declare function A(args: any[]): any[];
declare function not_a_tonyu_object(o: any): void;
declare function hasKey(k: any, obj: any): boolean;
declare function run(bootClassName: string): void;
declare function checkLoop(): void;
declare function resetLoopCheck(disableTime: number): void;
declare function is(obj: any, klass: any): any;
declare function load(options: ProjectOptions, definitions: () => void): void;
declare const Tonyu: {
    thread: typeof thread;
    supports_await: boolean;
    klass: {
        addMeta: typeof addMeta;
        removeMeta(n: string): void;
        removeMetaAll(ns: string): void;
        getMeta(k: string | Function): Meta;
        ensureNamespace(top: ClassTreeRoot, nsp: string): any;
        hasNamespace(top: ClassTreeRoot, nsp: string): boolean;
        propReg: RegExp;
        property: {
            isPropertyMethod(name: string): RegExpExecArray | null;
            methodFor(type: "get" | "set", name: string): string;
        };
        define(params: ClassDefinition): TonyuClass;
        getDependingClasses(_k: Meta | TonyuClass): Meta[];
    };
    bless: typeof bless;
    extend: typeof extend;
    messages: typeof R;
    load: typeof load;
    loadEvent: (e: any) => void;
    globals: {
        [key: string]: any;
    };
    classes: ClassTreeRoot;
    classMetas: {
        [key: string]: Meta;
    };
    setGlobal: typeof setGlobal;
    getGlobal: typeof getGlobal;
    getClass: typeof getClass;
    timeout: typeof timeout;
    bindFunc: typeof bindFunc;
    not_a_tonyu_object: typeof not_a_tonyu_object;
    is: typeof is;
    hasKey: typeof hasKey;
    invokeMethod: typeof invokeMethod;
    callFunc: typeof callFunc;
    checkNonNull: typeof checkNonNull;
    iterator: typeof IT;
    iterator2: typeof IT2;
    run: typeof run;
    checkLoop: typeof checkLoop;
    resetLoopCheck: typeof resetLoopCheck;
    currentProject: null;
    currentThread: TonyuThread | null;
    runMode: boolean;
    onRuntimeError: (e: Error) => void;
    TError: typeof TError;
    VERSION: number;
    A: typeof A;
    ID: number;
};
export default Tonyu;
