declare function R(name: string, ...params: any[]): any;
declare namespace R {
    var setLocale: (locale: string) => void;
    var getLocale: () => "ja" | "en";
    var dicts: {
        ja: {
            MethodAlreadyDeclared: string;
            typeNotFound: string;
            cannotCallNonFunctionType: string;
            memberNotFoundInClass: string;
            expected: string;
            superClassIsUndefined: string;
            classIsUndefined: string;
            invalidLeftValue: string;
            fieldDeclarationRequired: string;
            duplicateKeyInObjectLiteral: string;
            cannotUseStringLiteralAsAShorthandOfObjectValue: string;
            breakShouldBeUsedInIterationOrSwitchStatement: string;
            continueShouldBeUsedInIterationStatement: string;
            cannotUseObjectLiteralAsTheExpressionOfStatement: string;
            undefinedMethod: string;
            undefinedSuperMethod: string;
            notAWaitableMethod: string;
            circularDependencyDetected: string;
            cannotWriteReturnInTryStatement: string;
            cannotWriteBreakInTryStatement: string;
            cannotWriteContinueInTryStatement: string;
            cannotWriteTwoOrMoreCatch: string;
            lexicalError: string;
            parseError: string;
            ambiguousClassName: string;
            cannotInvokeMethod: string;
            notAMethod: string;
            notAFunction: string;
            uninitialized: string;
            newIsRequiredOnInstanciate: string;
            bootClassIsNotFound: string;
            infiniteLoopDetected: string;
            blockScopedVarDeclConflict: string;
            duplicateVarDecl: string;
            superWithoutMethodNameIsNotAllowedHere: string;
        };
        en: {
            MethodAlreadyDeclared: string;
            typeNotFound: string;
            cannotCallNonFunctionType: string;
            memberNotFoundInClass: string;
            expected: string;
            superClassIsUndefined: string;
            classIsUndefined: string;
            invalidLeftValue: string;
            fieldDeclarationRequired: string;
            duplicateKeyInObjectLiteral: string;
            cannotUseStringLiteralAsAShorthandOfObjectValue: string;
            breakShouldBeUsedInIterationOrSwitchStatement: string;
            continueShouldBeUsedInIterationStatement: string;
            cannotUseObjectLiteralAsTheExpressionOfStatement: string;
            undefinedMethod: string;
            undefinedSuperMethod: string;
            notAWaitableMethod: string;
            circularDependencyDetected: string;
            cannotWriteReturnInTryStatement: string;
            cannotWriteBreakInTryStatement: string;
            cannotWriteContinueInTryStatement: string;
            cannotWriteTwoOrMoreCatch: string;
            lexicalError: string;
            parseError: string;
            ambiguousClassName: string;
            cannotInvokeMethod: string;
            notAMethod: string;
            notAFunction: string;
            uninitialized: string;
            newIsRequiredOnInstanciate: string;
            bootClassIsNotFound: string;
            infiniteLoopDetected: string;
            blockScopedVarDeclConflict: string;
            duplicateVarDecl: string;
        };
    };
}
export default R;
